# Mockamap Parameters
update_freq: 0.5

## box edge length, unit meter
resolution: 0.35

## Perlin Noise
type: 1
# 5112, 5114, 5115 provides tough obstacles
seed: 5115
complexity: 0.024
fill: 0.105
fractal: 1
attenuation: 0.3
## map size unit meter
x_length: 40
y_length: 40
z_length: 15

## Pillars
# type: 2
# seed: 111
# width_min: 1.5
# width_max: 1.5
# obstacle_number: 70
## map size unit meter
#x_length: 40
#y_length: 40
#z_length: 15